name: 'Create gh-pages If It Does Not Exist'
description: 'Create gh-pages if it does not exist'
author: "Christopher Daveport"
runs:
  using: "composite"
  steps:
    - name: Branch name
      id: branch_name
      shell: bash
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - id: github-pages-exists
      run: |
        existed_in_remote=$(git ls-remote --heads origin gh-pages)

        if [[ -z ${existed_in_remote} ]]; then
          echo "Creating gh-pages branch"
          git config --global user.email "christopherdavenport@users.noreply.github.com"
          git config --global user.name "Christopher Davenport"
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initializing gh-pages branch"
          git push origin gh-pages
          git checkout ${{steps.branch_name.outputs.SOURCE_NAME}}
          echo "Created gh-pages branch"
        else
          echo "Branch gh-pages already exists"
        fi
      shell: bash

